apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:  
      containers:
        - name: server
          image: server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: DB_HOST
              value: postgres-service
            - name: REDIS_HOST
              value: redis-service
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
              