apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:  
      containers:
        - name: ws
          image: ws-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: DB_HOST
              value: postgres-service
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
              